version: "3.9"
services:
  client:
    network_mode: host
    build: .
    env_file: .env
    container_name: Client
    volumes:
      - type: bind
        source: ./client_volume
        target: /var/www/html/client_volume
        read_only: false
