version: "3.9"
services:
  client:
    network_mode: host
    build: .
    env_file: .env
    environment:
      - LOG_FILE_PATH
    volumes:
      - type: bind
        source: ./client_volume
        target: ${LOG_FILE_PATH}
        read_only: false
