version: "3.9"
services:
  server:
    extends:
      file: ./Server/docker-compose.yml
      service: server
  client:
    extends:
      file: ./Client/docker-compose.yml
      service: client
    depends_on:
      - server
