version: "3.9"
services:
  server:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - type: bind
        source: ./server_volume
        target: ${LOG_FILE_PATH}
        read_only: false