version: "3.9"
services:
  server:
    build: .
    ports:
      - "8000:8000"
    container_name: Server
    command: python3.9 -m aiohttp.web -H 0.0.0.0 -P 8000 main:web_app
    env_file: .env
    volumes:
      - type: bind
        source: ./server_volume
        target: '/var/www/html/server_volume'
        read_only: false