openapi: 3.0.1
info:
  title: GetTableAsync
  description: 'With this server you can get first n json formatted rows of a *.csv table with students performance data.'
  contact:
    email: arkkav@mail.ru
  version: 1.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/Arkkav/GetTableAsync/1.0.0
tags:
  - name: Student
    description: Students perfotrmance info
paths:
  /:
    get:
      tags:
        - Student
      summary: Get first n rows
      description: Return json with n first rows of a table
      parameters:
      - name: n
        in: query
        description: Number of first rows to get
        required: true
        schema:
          type: integer
          minimum: 0
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Student'
        '400':
          description: Invalid n parameter supplied
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    example: 'Parameter n should be defined as integer.'
      security:
        []
components:
  schemas:
    Student:
      type: object
      properties:
        gender:
          type: string
          enum:
            - female
            - male
        race/ethnicity:
          type: string
          enum:
            - group A
            - group B
            - group C
            - group D
            - group E
        parental level of education:
          type: string
          enum:
            - bachelor's degree
            - some college
            - master's degree
            - high school
            - associate's degree
          example: bachelor's degree
        lunch:
          type: string
          enum:
            - standard
            - free/reduced
        test preparation course:
          type: string
          enum:
            - completed
            - none
        math score:
          type: integer
          minimum: 0
          maximum: 100
          format: int8
          example: 81
        reading score:
          type: integer
          minimum: 0
          maximum: 100
          format: int8
          example: 72
        writing score:
          type: integer
          format: int8
          minimum: 0
          maximum: 100
          example: 66